spring:
  application:
    name: seefly
  rocketmq:
    namesrv-addr: 192.168.0.160:9876
    producer:
      instanceName: ROCKETMQ_DEMO
    consumer:
      subscribe: TOPIC_A
    topic:
      event-topic: TOPIC_B